MyMDB/urls.py
import debug_toolbar
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import core.urls
import user.urls
from MyMDB import settings

MEDIA_FILE_PATHS = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core')),

    url('^debug/', include(debug_toolbar.urls))
] + MEDIA_FILE_PATHS

core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name='MovieList'),
    path('movies/top', views.TopMovies.as_view(), name='TopMovies'),

    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='PersonDetail'),

    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),

    path('movie/<int:movie_id>/image/upload', views.ImageUpload.as_view(), name='ImageUpload'),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title> {% block title %} MyMBD {% endblock %}</title>
    <style>
        .mymbd-masthead {
            background-color: #EEEEEE;
            margin-bottom: 1em;
        }
    </style>
</head>

<body>
<div class="mymbd-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand"> MyMBD</div>
            <a class="nav-link" href="{% url 'core:MovieList' %}"> Movies </a>
            <a class="nav-link mr-auto" href="{% url 'core:TopMovies' %}"> Top 10 movies </a>
            {% if user.is_authenticated %}
                <span class="navbar-text"> Salut {{ user }} </span>
                <a class="nav-link" href="{% url 'user:logout' %}"> Logout </a>
            {% else %}
                <a class="nav-link" href="{% url 'user:login' %}"> Login </a>
            {% endif %}
        </nav>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-8 mymbd-main">
            {% block main %} {% endblock %}
        </div>

        <div class="col-sm-3 offset-sm-1 mymbd-sidebar">
            {% block sidebar %} {% endblock %}
        </div>

    </div>
</div>

</body>

</html>